/**
 * Per-referee detail — every WC match they officiated.
 *
 * URL: /wc-explorer/referees/{slug}/
 *
 * Slug is the lowercase, accent-stripped, hyphenated form of the
 * name (e.g. `ravshan-irmatov`). Generated by the wc-api's
 * /referees endpoint so it stays stable across deploys.
 *
 * 404 for unknown ids.
 */

import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getReferee } from '@/lib/wc-api';
import { Flag } from '@/components/Flag';

export const dynamic = 'force-dynamic';

interface PageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const ref = await getReferee(id);
  if (!ref) return { title: 'Referee' };
  return {
    title: `${ref.name} — World Cup matches officiated`,
    description: `${ref.name} (${ref.country ?? 'unknown country'}) officiated ${ref.totalMatches} matches across ${ref.tournaments} FIFA World Cups (${ref.years[0]}–${ref.years[ref.years.length - 1]}). Complete match list with scores, venues, and stages.`,
    alternates: { canonical: `/referees/${ref.id}/` },
  };
}

const STAGE_SHORT: Record<string, string> = {
  round_of_32:    'R32',
  round_of_16:    'R16',
  quarter_final:  'QF',
  semi_final:     'SF',
  third_place:    '3rd',
  final:          'F',
};
function shortStage(raw: string): string {
  if (raw.startsWith('group_')) return `Grp ${raw.slice(6).toUpperCase()}`;
  return STAGE_SHORT[raw] ?? raw;
}
function isKnockout(raw: string): boolean { return !raw.startsWith('group_'); }
function formatDate(iso: string): string {
  try {
    const [y, m, d] = iso.split('-').map(Number);
    const mn = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m! - 1] ?? '?';
    return `${mn} ${d}, ${y}`;
  } catch { return iso; }
}

export default async function RefereePage({ params }: PageProps) {
  const { id } = await params;
  const ref = await getReferee(id);
  if (!ref) notFound();

  const span = ref.years[0] === ref.years[ref.years.length - 1]
    ? `${ref.years[0]}`
    : `${ref.years[0]}–${ref.years[ref.years.length - 1]}`;

  return (
    <>
      {/* Hero */}
      <section className="border-b border-ink-800 bg-grid">
        <div className="max-w-7xl mx-auto px-6 py-10 sm:py-12">
          <div className="text-xs mb-4">
            <Link href="/referees/" className="text-brand-400 hover:underline">← All referees</Link>
          </div>
          <div className="flex items-baseline gap-3 flex-wrap">
            <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight">{ref.name}</h1>
            {ref.country && (
              <span className="inline-flex items-center gap-2 text-ink-300">
                <Flag country={ref.country} size={20} />
                <span className="text-base">{ref.country}</span>
              </span>
            )}
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-8">
            <Stat label="Matches" value={ref.totalMatches.toString()} hint="across all WCs" />
            <Stat label="World Cups" value={ref.tournaments.toString()} hint={span} />
            <Stat
              label="Knockout matches"
              value={String(['round_of_32','round_of_16','quarter_final','semi_final','third_place','final']
                .reduce((s, k) => s + (ref.byStage[k] ?? 0), 0))}
              hint={ref.byStage.final ? `${ref.byStage.final} × final` : ''}
            />
            <Stat
              label="Group-stage matches"
              value={String(Object.entries(ref.byStage)
                .filter(([k]) => k.startsWith('group_'))
                .reduce((s, [, v]) => s + v, 0))}
            />
          </div>
        </div>
      </section>

      {/* Match table */}
      <section className="max-w-7xl mx-auto px-6 py-10">
        <div className="bg-ink-900 border border-ink-800 rounded-2xl overflow-hidden">
          <header className="px-5 py-3 border-b border-ink-800/60">
            <h2 className="text-sm font-bold text-white">Match history — newest first</h2>
          </header>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-ink-800/40 text-left text-[10px] uppercase tracking-widest text-ink-400">
                <tr>
                  <th className="px-4 py-2 font-semibold">Date</th>
                  <th className="px-4 py-2 font-semibold">WC</th>
                  <th className="px-4 py-2 font-semibold">Stage</th>
                  <th className="px-4 py-2 font-semibold">Match</th>
                  <th className="px-4 py-2 font-semibold text-center">Score</th>
                  <th className="px-4 py-2 font-semibold">Venue</th>
                </tr>
              </thead>
              <tbody>
                {ref.matches.map((m) => {
                  const ko = isKnockout(m.stage);
                  const hasResult = m.homeScore != null && m.awayScore != null;
                  return (
                    <tr key={m.id} className="border-t border-ink-800/60 hover:bg-ink-800/30">
                      <td className="px-4 py-2.5 text-ink-300 text-xs whitespace-nowrap">
                        {formatDate(m.date)}
                      </td>
                      <td className="px-4 py-2.5">
                        <Link href={`/${m.year}/`} className="text-brand-400 hover:underline font-mono tabular-nums">
                          {m.year}
                        </Link>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className={`inline-block text-[10px] uppercase tracking-widest font-semibold px-2 py-0.5 rounded ${
                          ko
                            ? m.stage === 'final'
                              ? 'bg-accent-gold/15 text-accent-gold border border-accent-gold/40'
                              : 'bg-brand-500/20 text-brand-300 border border-brand-500/40'
                            : 'bg-ink-700/40 text-ink-300 border border-ink-700'
                        }`}>{shortStage(m.stage)}</span>
                      </td>
                      <td className="px-4 py-2.5">
                        <div className="flex items-center gap-2 text-ink-100">
                          {m.homeTeam && <Flag country={m.homeTeam.trim()} />}
                          <span className="font-medium truncate">{m.homeTeam ?? '—'}</span>
                          <span className="text-ink-500 px-1">vs</span>
                          {m.awayTeam && <Flag country={m.awayTeam.trim()} />}
                          <span className="font-medium truncate">{m.awayTeam ?? '—'}</span>
                        </div>
                      </td>
                      <td className="px-4 py-2.5 text-center font-mono tabular-nums text-white">
                        {hasResult ? `${m.homeScore}–${m.awayScore}` : '—'}
                      </td>
                      <td className="px-4 py-2.5 text-xs text-ink-300 truncate">
                        {m.stadium}{m.city ? <span className="text-ink-500">, {m.city}</span> : null}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          <div className="px-4 py-2 border-t border-ink-800 text-[10px] font-mono text-ink-500">
            <span className="text-brand-400">GET /referees/{ref.id}</span>
          </div>
        </div>
      </section>
    </>
  );
}

function Stat({ label, value, hint }: { label: string; value: string; hint?: string }) {
  return (
    <div className="bg-ink-900/80 backdrop-blur border border-ink-800 rounded-xl p-4">
      <div className="text-2xl sm:text-3xl font-black text-white">{value}</div>
      <div className="text-[10px] uppercase tracking-widest text-ink-300 mt-1">{label}</div>
      {hint && <div className="text-[10px] text-ink-500 mt-0.5">{hint}</div>}
    </div>
  );
}
